name: Debian Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Debian
      run: |
        docker build -t debian-builder .
        docker run --rm -v $(pwd):/app debian-builder

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: debian-package
        path: /path/to/debian/package.deb
